name: primeira-pipeline
on: 
  push: 
    branches: ["main"]
  workflow_dispatch: 
jobs:
  primeiro-job:
    name: "Meu Primeiro Job"
    runs-on: ubuntu-latest
    steps:
      - name: "Minha primeiro ação"
        run: echo "Hello World"
      - name: "Segunda ação"
        run: |
          echo "Você criou seu primeiro workflow"
          echo "Parabêns"
      - name: "Script Python"
        run: |
          variavel = "Hello World"
          print(variavel)
        shell: python
  segundo-job:
    name: "Instalação do Ambiente NodeJS"
    runs-on: ubuntu-latest
    needs: [primeiro-job]
    steps:
      - name: "Verificação da versão do NodeJS atual"
        run: node --version
      - name: "Definição da versão 24 do NodeJS"
        uses: actions/setup-node@v6
        with:
          node-version: '24.11.1'
      - name: "Verificação da versão do NodeJS depois de instalar"
        run: node --version
